create table if not exists notes (
  id int primary key generated by default as identity,
  note_name varchar(100) not null,
  modified timestamp default now() not null,
  folder_id int references folders(id) on delete cascade not null,
  content text 
);